export const FSM_STATES = [
    {
        id: "INTAKE", label: "Intake", description: "Initial case assessment and fact gathering",
        color: "#2dd4bf", icon: "📥",
        allowedTransitions: ["ACAS_CONCILIATION"],
        entryActions: ["Run gap analysis", "Identify claim types", "Calculate time limits"],
        deadlines: [{ label: "Complete assessment", daysFromEntry: 7, critical: false }],
        requiredDocuments: ["Employment contract", "Dismissal letter", "Relevant correspondence"],
    },
    {
        id: "ACAS_CONCILIATION", label: "ACAS Early Conciliation", description: "Mandatory pre-claim conciliation period (up to 6 weeks)",
        color: "#2dd4bf", icon: "🤝",
        allowedTransitions: ["ET1_FILED"],
        entryActions: ["Contact ACAS", "Start limitation clock pause", "Document conciliation offer"],
        deadlines: [{ label: "ACAS period expires", daysFromEntry: 42, critical: true }],
        requiredDocuments: ["ACAS certificate"],
    },
    {
        id: "ET1_FILED", label: "ET1 Filed", description: "Claim form submitted to Employment Tribunal",
        color: "#2dd4bf", icon: "📝",
        allowedTransitions: ["ET3_AWAITED"],
        entryActions: ["File ET1", "Serve on respondent", "Pay issue fee (if applicable)"],
        deadlines: [{ label: "Primary limitation", daysFromEntry: 0, critical: true }],
        requiredDocuments: ["ET1 form", "ACAS certificate", "Particulars of claim"],
    },
    {
        id: "ET3_AWAITED", label: "Awaiting ET3", description: "Waiting for respondent's response (28 days)",
        color: "#fbbf24", icon: "⏳",
        allowedTransitions: ["PRELIMINARY_HEARING", "DEFAULT_JUDGMENT"],
        entryActions: ["Monitor 28-day deadline", "Prepare for default judgment application"],
        deadlines: [{ label: "ET3 response deadline", daysFromEntry: 28, critical: true }, { label: "Default judgment application", daysFromEntry: 35, critical: false }],
        requiredDocuments: [],
    },
    {
        id: "DEFAULT_JUDGMENT", label: "Default Judgment", description: "Respondent failed to respond — apply for default judgment",
        color: "#2dd4bf", icon: "⚡",
        allowedTransitions: ["JUDGMENT"],
        entryActions: ["Apply under Rule 21"],
        deadlines: [],
        requiredDocuments: ["Default judgment application"],
    },
    {
        id: "PRELIMINARY_HEARING", label: "Preliminary Hearing", description: "Case management — directions, disclosure timetable, hearing dates",
        color: "#818cf8", icon: "🗓️",
        allowedTransitions: ["DISCLOSURE"],
        entryActions: ["Prepare case summary", "Draft proposed directions", "Identify issues"],
        deadlines: [{ label: "Submit agenda / case summary", daysFromEntry: -7, critical: true }],
        requiredDocuments: ["Case summary", "Proposed directions", "Chronology"],
    },
    {
        id: "DISCLOSURE", label: "Disclosure", description: "Exchange of relevant documents per tribunal order",
        color: "#818cf8", icon: "📂",
        allowedTransitions: ["WITNESS_STATEMENTS"],
        entryActions: ["Prepare disclosure list", "Review respondent disclosure", "Identify gaps"],
        deadlines: [{ label: "Disclosure deadline", daysFromEntry: 28, critical: true }],
        requiredDocuments: ["Disclosure list", "Scott schedule (if applicable)"],
    },
    {
        id: "WITNESS_STATEMENTS", label: "Witness Statements", description: "Preparation and simultaneous exchange of witness statements",
        color: "#818cf8", icon: "📜",
        allowedTransitions: ["BUNDLE_PREP"],
        entryActions: ["Draft witness statements", "Prepare for exchange"],
        deadlines: [{ label: "Exchange deadline", daysFromEntry: 28, critical: true }],
        requiredDocuments: ["Claimant witness statement", "Supporting witness statements"],
    },
    {
        id: "BUNDLE_PREP", label: "Bundle Preparation", description: "Agreed hearing bundle compiled",
        color: "#818cf8", icon: "📚",
        allowedTransitions: ["FINAL_HEARING"],
        entryActions: ["Agree bundle contents", "Paginate and index"],
        deadlines: [{ label: "Bundle deadline", daysFromEntry: 14, critical: true }],
        requiredDocuments: ["Hearing bundle", "Index"],
    },
    {
        id: "FINAL_HEARING", label: "Final Hearing", description: "Full merits hearing before tribunal panel",
        color: "#f472b6", icon: "⚖️",
        allowedTransitions: ["JUDGMENT"],
        entryActions: ["Prepare skeleton argument", "Authorities bundle", "Run Shadow-Opponent debate"],
        deadlines: [{ label: "Skeleton argument due", daysFromEntry: -7, critical: true }, { label: "Authorities bundle due", daysFromEntry: -3, critical: true }],
        requiredDocuments: ["Skeleton argument", "Authorities bundle", "Cast list", "Chronology"],
    },
    {
        id: "JUDGMENT", label: "Judgment", description: "Tribunal decision received",
        color: "#f472b6", icon: "📋",
        allowedTransitions: ["APPEAL"],
        entryActions: ["Request written reasons within 14 days", "Assess grounds of appeal"],
        deadlines: [{ label: "Request written reasons", daysFromEntry: 14, critical: true }, { label: "Appeal deadline (from written reasons)", daysFromEntry: 56, critical: true }],
        requiredDocuments: ["Judgment", "Written reasons"],
    },
    {
        id: "APPEAL", label: "Appeal (EAT)", description: "Notice of Appeal within 42 days of written reasons",
        color: "#ef4444", icon: "🔺",
        allowedTransitions: [],
        entryActions: ["Draft Notice of Appeal", "Identify error of law", "Prepare Rule 3(10) arguments"],
        deadlines: [{ label: "Notice of Appeal deadline", daysFromEntry: 42, critical: true }],
        requiredDocuments: ["Notice of Appeal", "Appellant's skeleton", "ET judgment + reasons"],
    },
];

export const FSM_STORAGE_KEY = "tribunal_harness_fsm";
